"""
    Contains the business logic for fetching Github API content and caching it
    in a central "master" cache. The cache is accessed via "redlock" so that
    when Github API content expires, only a single node (of potentially many)
    will hit Github's API to refresh the cache.
"""
import time, requests, json
from config import Config # See common/config.py
import redis
from redlock import RedLock

cachesrv = redis.StrictRedis(
    host=Config.MASTER_CACHE_HOST,
    port=Config.MASTER_CACHE_PORT,
    password=Config.MASTER_CACHE_PASSWORD,
    db=0)

# NOTE(james) We use this decorator on the class below to cache the content
# generated by the methods.
def master_cache(func):
    def wrapper(*args):
        conn = [{
            'host': Config.MASTER_CACHE_HOST,
            'port': Config.MASTER_CACHE_PORT,
            'password': Config.MASTER_CACHE_PASSWORD,
            'db': 0
        }]
        k = str(args[0].__class__) + func.__name__
        v = cachesrv.get(k)
        if not v:
            with RedLock(k + '.lock', connection_details=conn):
                v = json.dumps(func(*args))
                cachesrv.set(k, v, Config.MASTER_CACHE_TTL)
        return v
    return wrapper


class ApiGrab(object):
    def __init__(self, api_prefix):
        self.api_prefix = api_prefix
        self.headers = {}

    def get(self, url):
        return json.loads(self.get_req(url).content)

    def get_req(self, url = ''):
        if url.startswith('/'):
            return requests.get(self.api_prefix + url, headers = self.headers)
        else:
            return requests.get(url, headers = self.headers)

    def get_all(self, req):
        data = json.loads(req.content)
        if type(data) is not list:
            return data
        while req.links and 'next' in req.links:
            req = self.get_req(req.links['next']['url'])
            data += json.loads(req.content)
        return data


class GithubGrab(ApiGrab):
    def __init__(self):
        super(GithubGrab, self).__init__(Config.GITHUB_API_PREFIX)
        if Config.GITHUB_API_TOKEN:
            self.headers['Authorization'] = 'token ' + Config.GITHUB_API_TOKEN

    @master_cache
    def netflix_orgs(self):
        return json.loads(self.get_req('/orgs/Netflix').content)

    @master_cache
    def github_root(self):
        return json.loads(self.get_req(self.api_prefix).content)

    @master_cache
    def all_netflix_repos(self):
        return self.get_all(self.get_req('/orgs/Netflix/repos'))

    @master_cache
    def all_netflix_members(self):
        return self.get_all(self.get_req('/orgs/Netflix/members'))
